# Generated by Django 2.1.7 on 2019-04-28 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20190425_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webcasename', models.CharField(max_length=200, verbose_name='Case_Name')),
                ('webtestresult', models.BooleanField(verbose_name='Test_Result')),
                ('webtester', models.CharField(max_length=16, verbose_name='Tester')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create_Time')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Web_Test_Case',
                'verbose_name_plural': 'Web_Test_Case',
            },
        ),
        migrations.CreateModel(
            name='Webcasestep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webcasename', models.CharField(max_length=200, verbose_name='Case_Name')),
                ('webteststep', models.CharField(max_length=200, verbose_name='Test_Step')),
                ('webtestobjname', models.CharField(max_length=200, verbose_name='Object_name')),
                ('webfindmethod', models.CharField(max_length=200, verbose_name='Find_Method')),
                ('webevelment', models.CharField(max_length=800, verbose_name='Evelment')),
                ('weboptmethod', models.CharField(max_length=200, verbose_name='Operate_Method')),
                ('webtestdata', models.CharField(max_length=200, null=True, verbose_name='Test_Data')),
                ('webassertdata', models.CharField(max_length=200, verbose_name='Assert_Data')),
                ('webtestresult', models.BooleanField(verbose_name='Test_Result')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create_Time')),
                ('Webcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.Webcase')),
            ],
        ),
    ]
