# Generated by Django 2.1.7 on 2019-04-26 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20190425_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bugname', models.CharField(max_length=64, verbose_name='Bug_Name')),
                ('bugdetail', models.CharField(max_length=200, verbose_name='Detail')),
                ('bugstatus', models.CharField(choices=[('Activate', 'Activate'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Activate', max_length=200, null=True, verbose_name='Solution_State')),
                ('buglevel', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=200, null=True, verbose_name='Bug_Level')),
                ('bugcreater', models.CharField(max_length=200, verbose_name='Creater')),
                ('bugassign', models.CharField(max_length=200, verbose_name='Assign')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create_Time')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Bug_Manage',
                'verbose_name_plural': 'Bug_Manage',
            },
        ),
    ]
