# Generated by Django 2.1.7 on 2019-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product_manage', 'verbose_name_plural': 'product_manage'},
        ),
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productdesc',
            field=models.CharField(max_length=200, verbose_name='product_desc'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producter',
            field=models.CharField(max_length=200, verbose_name='producter'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productname',
            field=models.CharField(max_length=64, verbose_name='product_name'),
        ),
    ]
