# Generated by Django 2.1.7 on 2019-04-26 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20190425_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apistep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiname', models.CharField(max_length=100, verbose_name='Interface_name')),
                ('apiurl', models.CharField(max_length=200, verbose_name='URL_Address')),
                ('apistep', models.CharField(max_length=100, null=True, verbose_name='Test_Procedure')),
                ('apiparamvalue', models.CharField(max_length=800, verbose_name='Request_Parameters_and_Values')),
                ('apimethod', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=200, null=True, verbose_name='Request_Method')),
                ('apiresult', models.CharField(max_length=200, verbose_name='Expected_Results')),
                ('apiresponse', models.CharField(max_length=5000, null=True, verbose_name='Response_Data')),
                ('apistatus', models.BooleanField(verbose_name='Whether_to_Pass')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create_Time')),
            ],
        ),
        migrations.CreateModel(
            name='Apitest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apitestname', models.CharField(max_length=64, verbose_name='Process_Interface_Name')),
                ('apitestdesc', models.CharField(max_length=64, null=True, verbose_name='Description')),
                ('apitester', models.CharField(max_length=16, verbose_name='Tester')),
                ('apitestresult', models.BooleanField(verbose_name='Test_Result')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create_Time')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Process_Scenario_Interface',
                'verbose_name_plural': 'Process_Scenario_Interface',
            },
        ),
        migrations.AddField(
            model_name='apistep',
            name='Apitest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Apitest'),
        ),
    ]
