# Generated by Django 2.1.7 on 2019-04-26 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190425_1503'),
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiname', models.CharField(max_length=100, verbose_name='Interface_name')),
                ('apiurl', models.CharField(max_length=200, verbose_name='URL_Address')),
                ('apiparamvalue', models.CharField(max_length=800, verbose_name='Request_Parameters_and_Values')),
                ('apimethod', models.CharField(choices=[('0', 'get'), ('1', 'post'), ('2', 'put'), ('3', 'delete'), ('4', 'patch')], default='0', max_length=200, verbose_name='Request_Method')),
                ('apiresult', models.CharField(max_length=200, verbose_name='Expected_Results')),
                ('apistatus', models.BooleanField(verbose_name='Whether_to_Pass')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create_Time')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Single_Scene_Interface',
                'verbose_name_plural': 'Single_Scene_Interface',
            },
        ),
    ]
