# Generated by Django 2.1.7 on 2019-04-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setname', models.CharField(max_length=64, verbose_name='System_Name')),
                ('setvalue', models.CharField(max_length=200, verbose_name='System_Setting')),
            ],
            options={
                'verbose_name': 'System_Setting',
                'verbose_name_plural': 'System_Setting',
            },
        ),
    ]
